#%RAML 1.0
title: hr-exp-api
description: API to intreact with HR System
mediaType: application/json

types:
  Error: !include datatypes/Error.raml
  Staff: !include datatypes/Staff.raml
  StaffResp: !include datatypes/StaffResp.raml

traits:
  clientIdRequired: !include traits/hasClientIdHeader.raml

/staff:
#List staff members
    get:
      is:
        - clientIdRequired
      description: Retrieve a list of all staff members
      queryParameters:
        firstName?:
          description: First Name of Staff member
          type: string
          example: Jane
        lastName?:
          description: Last Name of Staff member
          type: string
          example: Citizen
        role?:
          description: Staff member role
          type: string
          example: "Manager"
        active?:
          description: Is Staff member active
          type: boolean
          example: true
        ps?:
          description: Page size for pagination requests
          type: number
          example: 50
        p?:
          description: Page number for pagination requests
          type: number
          example: 1
      responses:
        200:
          body:
            application/json:
              type: StaffResp
              example: !include ./examples/StaffsExample.raml
        400:
          description: Error in user request
          body:
            application/json:
              type: Error
              example: !include ./examples/ErrorExample.raml
    post:
    #Create new staff member
        is:
          - clientIdRequired
        description: Create a new staff member.
        body:
          application/json:
            type: Staff
        responses:
          201:
            description: Staff member created successfully.
            body: 
              text/plain: 
                example: |
                  Staff member Sucessfully created with ID 1
          401:
            description: Unauthorized access 
            body: 
              text/plain: 
                example: |
                  Unauthorized. Special privilege token required
    /{staffId}:
    #Get specific staff member
      get:
        is:
          - clientIdRequired
        description: Get a specific staff member
        responses:
          200:
            body:
              application/json:
                type: Staff
                example: !include ./examples/StaffExample.raml
          400:
            description: Error in user request
            body:
              application/json:
                type: Error
                example: !include ./examples/ErrorExample.raml
          401:
            description: Unauthorized access 
            body:
              application/json:
                type: Error
                example: !include ./examples/ErrorExample.raml
      #offboard a staff member
      delete:
        is:
          - clientIdRequired
        description: Delete an exisiting staff member
        responses:
          204:
            description: Offboarding sucessfull
            body: 
              text/plain: 
                example: |
                  Staff member Sucessfully offboarded
          400:
            description: Error in user request
            body:
              application/json:
                type: Error
                example: !include ./examples/ErrorExample.raml
          401:
            description: Unauthorized access 
            body:
              application/json:
                type: Error
                example: !include ./examples/ErrorExample.raml
      #update a staff member
      put:
        is:
          - clientIdRequired
        description: Update an exisiting staff member
        body:
          application/json:
            type: Staff
        responses:
          201:
            description: Sucessfull Update
            body: 
              text/plain: 
                example: |
                  Staff member Sucessfully updated
          400:
            description: Error in user request
            body:
              application/json:
                type: Error
                example: !include ./examples/ErrorExample.raml
          401:
            description: Unauthorized access 
            body:
              application/json:
                type: Error
                example: !include ./examples/ErrorExample.raml

/notification:
  /create:
    post:
      is:
          - clientIdRequired
      description: Notify the API of changed staff records
      body:
        application/json:
          type: Staff[]
      responses:
        201:
          description: Notification received successfully
          body: 
            text/plain: 
              example: |
                Notification processed sucessfully
        400:
            description: Error in user request
            body:
              application/json:
                type: Error
                example: !include ./examples/ErrorExample.raml
  /update:
    put:
      is:
          - clientIdRequired
      description: Notify the API of changed staff records
      body:
        application/json:
          type: Staff[]
      responses:
        201:
          description: Notification received successfully
          body: 
            text/plain: 
              example: |
                Notification processed sucessfully
        400:
            description: Error in user request
            body:
              application/json:
                type: Error
                example: !include ./examples/ErrorExample.raml
  